{
    "name": "Speller",
    "version": "1.1.14",
    "icon": "fas fa-spell-check",
    "category": "assistance",
    "author": "Psychokiller1888",
    "maintainers": [
        "maxbachmann"
    ],
    "desc": "Ask alice how to spell any word!",
    "aliceMinVersion": "1.0.0-b4",
    "pipRequirements": [],
    "systemRequirements": [],
    "conditions": {
        "lang": [
            "en",
            "fr",
	    "pt"
        ],
        "asrArbitraryCapture": true
    }
}
