{
    "name": "Speller",
    "version": "1.1.4",
    "icon": "fab fa-battle-net",
    "category": "assistance",
    "author": "Psychokiller1888",
    "maintainers": [
        "maxbachmann"
    ],
    "desc": "Ask alice how to spell any word!",
    "aliceMinVersion": "1.0.0-b3",
    "pipRequirements": [],
    "systemRequirements": [],
    "conditions": {
        "lang": [
            "en",
            "fr"
        ],
        "asrArbitraryCapture": true
    }
}